document.addEventListener("DOMContentLoaded", async () => {
  const cliente = window.STESIN_SUPABASE, $ = (s) => document.querySelector(s);
  if (!cliente) return;
  const { data: { user } = {} } = await cliente.auth.getUser(); if (!user) return;
  const { data: perfil } = await cliente.from("perfiles").select("rol,nombre,activo").eq("id", user.id).single(); if (!perfil?.activo) return location.replace("login.html?estado=inactivo");
  const staff = ["admin","docente"].includes(perfil.rol), escapar = (v="") => String(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  $("#academicWelcome").textContent = staff ? `Gestión académica · ${perfil.nombre}` : `Hola, ${perfil.nombre}`;
  $("#academicSummary").textContent = staff ? "Publica actividades de tus materias y revisa las entregas de los estudiantes." : "Entrega tareas y realiza evaluaciones. Tus resultados quedan registrados.";
  if (staff) $("#herramientasDocente").hidden = false;
  const fecha = (valor) => valor ? new Date(valor).toLocaleString("es-PE", {dateStyle:"medium",timeStyle:"short"}) : "Sin fecha límite";

  async function cargarTareas(){ const {data:tareas,error}=await cliente.from("tareas_academicas").select("*").eq("activo",true).order("fecha_limite",{ascending:true}); const host=$("#listaTareas"); if(error){host.innerHTML='<p class="academic-empty">Ejecuta el SQL de la Etapa 2 para activar tareas.</p>';return;} const {data:entregas}=await cliente.from("entregas_tareas").select("*").eq("estudiante_id",user.id); const porTarea=new Map((entregas||[]).map(e=>[e.tarea_id,e])); host.innerHTML=(tareas||[]).map(t=>{const entrega=porTarea.get(t.id); return `<article class="academic-item"><h3>${escapar(t.titulo)}</h3><p><strong>${escapar(t.ciclo)} · ${escapar(t.materia)}</strong></p><p>${escapar(t.instrucciones)}</p><p class="due">Entrega: ${fecha(t.fecha_limite)}</p>${t.enlace_referencia?`<a class="text-link" href="${escapar(t.enlace_referencia)}" target="_blank" rel="noopener">Material de referencia →</a>`:""}${entrega?`<span class="score">${escapar(entrega.estado)}${entrega.calificacion!==null?` · Nota ${entrega.calificacion}/20`:""}</span><p>${escapar(entrega.comentario_docente||"")}</p>`:`<form data-entrega="${t.id}"><textarea name="comentario" placeholder="Comentario para el docente"></textarea><input name="enlace" type="url" placeholder="Enlace de tu archivo (opcional)"><input name="archivo" type="file"><button class="account-action">Entregar tarea</button></form>`}</article>`;}).join("")||'<p class="academic-empty">No hay tareas publicadas.</p>'; host.querySelectorAll("form[data-entrega]").forEach(f=>f.addEventListener("submit",entregarTarea)); }
  async function entregarTarea(e){e.preventDefault();const f=e.currentTarget,b=f.querySelector("button");b.disabled=true;let enlace=f.enlace.value.trim();const archivo=f.archivo.files[0];if(archivo){const ruta=`${user.id}/${Date.now()}-${archivo.name.replace(/[^\w.-]/g,"_")}`;const {error}=await cliente.storage.from("entregas-tareas").upload(ruta,archivo);if(error){alert(error.message);b.disabled=false;return;}enlace=`storage:${ruta}`;}const {error}=await cliente.from("entregas_tareas").insert({tarea_id:Number(f.dataset.entrega),estudiante_id:user.id,enlace_archivo:enlace||null,comentario_estudiante:f.comentario.value.trim()||null});if(error)alert("No se pudo entregar: "+error.message);await cargarTareas();}
  async function cargarEvaluaciones(){const {data:lista,error}=await cliente.from("evaluaciones").select("*").eq("activo",true).order("creado_en",{ascending:false});const host=$("#listaEvaluaciones");if(error){host.innerHTML='<p class="academic-empty">Ejecuta el SQL de la Etapa 2 para activar evaluaciones.</p>';return;}const {data:intentos}=await cliente.from("intentos_evaluacion").select("*").eq("estudiante_id",user.id);const realizados=new Map((intentos||[]).map(i=>[i.evaluacion_id,i]));host.innerHTML=(lista||[]).map(e=>{const intento=realizados.get(e.id);return `<article class="academic-item"><h3>${escapar(e.titulo)}</h3><p><strong>${escapar(e.ciclo)} · ${escapar(e.materia)}</strong></p><p>${escapar(e.instrucciones||"Responde las preguntas y envía una sola vez.")}</p>${intento?`<span class="score">Resultado: ${intento.puntaje}/${intento.puntaje_maximo}</span>`:`<button class="account-action" type="button" data-evaluacion="${e.id}">Iniciar evaluación</button><div id="evaluacion-${e.id}"></div>`}</article>`;}).join("")||'<p class="academic-empty">No hay evaluaciones publicadas.</p>';host.querySelectorAll("[data-evaluacion]").forEach(b=>b.addEventListener("click",abrirEvaluacion));}
  async function abrirEvaluacion(e){const b=e.currentTarget,id=Number(b.dataset.evaluacion),host=$("#evaluacion-"+id);b.disabled=true;const {data:preguntas,error}=await cliente.rpc("preguntas_para_evaluacion",{evaluacion_busqueda:id});if(error){host.innerHTML='<p class="academic-empty">No se pudo abrir la evaluación.</p>';return;}host.innerHTML=`<form data-form-evaluacion="${id}">${(preguntas||[]).map(p=>`<div class="question"><strong>${escapar(p.enunciado)}</strong>${(p.opciones||[]).map((op,i)=>`<label><input required type="radio" name="p-${p.id}" value="${i}"> ${escapar(op)}</label>`).join("")}</div>`).join("")}<button class="account-action">Enviar evaluación</button></form>`;host.querySelector("form").addEventListener("submit",enviarEvaluacion);}
  async function enviarEvaluacion(e){e.preventDefault();const form=e.currentTarget,id=Number(form.dataset.formEvaluacion),respuestas={};new FormData(form).forEach((v,k)=>{if(k.startsWith("p-"))respuestas[k.slice(2)]=Number(v)});const {data,error}=await cliente.rpc("enviar_evaluacion",{evaluacion_busqueda:id,respuestas_enviadas:respuestas});if(error){alert(error.message);return;}const r=data?.[0];alert(`Evaluación enviada. Puntaje: ${r?.puntaje ?? 0}/${r?.puntaje_maximo ?? 0}`);cargarEvaluaciones();}
  async function cargarEntregas(){if(!staff)return;const [{data,error},{data:personas}]=await Promise.all([cliente.from("entregas_tareas").select("id,tarea_id,estudiante_id,comentario_estudiante,enlace_archivo,estado,calificacion,tareas_academicas(titulo,ciclo,materia)").order("entregado_en",{ascending:false}),cliente.from("perfiles").select("id,nombre")]);const host=$("#listaEntregas");if(error){host.innerHTML='<p class="academic-empty">Las entregas aparecerán cuando se active el SQL.</p>';return;}const nombres=new Map((personas||[]).map(p=>[p.id,p.nombre]));host.innerHTML=(data||[]).map(x=>`<article class="academic-item"><h3>${escapar(x.tareas_academicas?.titulo||"Tarea")}</h3><p><strong>${escapar(nombres.get(x.estudiante_id)||"Estudiante")}</strong> · ${escapar(x.comentario_estudiante||"Sin comentario")}</p>${x.enlace_archivo?`<p>Archivo: ${escapar(x.enlace_archivo)}</p>`:""}<form data-revision="${x.id}"><select name="estado"><option value="revisado">Revisado</option><option value="requiere_correccion">Requiere corrección</option></select><input name="nota" type="number" min="0" max="20" step=".1" value="${x.calificacion??""}" placeholder="Nota /20"><textarea name="comentario" placeholder="Comentario para el estudiante"></textarea><button class="account-action">Guardar revisión</button></form></article>`).join("")||'<p class="academic-empty">Aún no hay entregas.</p>';host.querySelectorAll("form[data-revision]").forEach(f=>f.addEventListener("submit",revisarEntrega));}
  async function revisarEntrega(e){e.preventDefault();const f=e.currentTarget,{error}=await cliente.from("entregas_tareas").update({estado:f.estado.value,calificacion:f.nota.value?Number(f.nota.value):null,comentario_docente:f.comentario.value.trim()||null,revisado_en:new Date().toISOString()}).eq("id",f.dataset.revision);if(error)alert(error.message);else cargarEntregas();}
  if(staff){$("#formTarea").addEventListener("submit",async e=>{e.preventDefault();const d=new FormData(e.currentTarget),{error}=await cliente.from("tareas_academicas").insert({ciclo:d.get("ciclo"),materia:d.get("materia"),titulo:d.get("titulo"),instrucciones:d.get("instrucciones"),fecha_limite:d.get("fecha")||null,enlace_referencia:d.get("referencia")||null,creado_por:user.id});if(error)alert(error.message);else{e.currentTarget.reset();cargarTareas();}});$("#formEvaluacion").addEventListener("submit",async e=>{e.preventDefault();const d=new FormData(e.currentTarget),opciones=d.get("opciones").split("|").map(x=>x.trim()).filter(Boolean),{data,error}=await cliente.from("evaluaciones").insert({ciclo:d.get("ciclo"),materia:d.get("materia"),titulo:d.get("titulo"),creado_por:user.id}).select("id").single();if(error){alert(error.message);return;}const {error:ep}=await cliente.from("preguntas_evaluacion").insert({evaluacion_id:data.id,enunciado:d.get("pregunta"),opciones,respuesta_correcta:Number(d.get("correcta"))-1});if(ep)alert(ep.message);else{e.currentTarget.reset();cargarEvaluaciones();}});}
  await Promise.all([cargarTareas(),cargarEvaluaciones(),cargarEntregas()]);
});
