document.addEventListener("DOMContentLoaded", async () => {
  const cliente = window.STESIN_SUPABASE, $ = (s) => document.querySelector(s);
  if (!cliente) return;
  const { data: { user } = {} } = await cliente.auth.getUser(); if (!user) return;
  const { data: perfil } = await cliente.from("perfiles").select("rol,nombre,activo,ciclo_actual").eq("id", user.id).single();
  if (!perfil?.activo) return location.replace("login.html?estado=inactivo");
  const staff = ["admin", "docente"].includes(perfil.rol), esc = (v = "") => String(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const fecha = (valor) => valor ? new Date(valor).toLocaleString("es-PE", { dateStyle: "medium", timeStyle: "short" }) : "Sin fecha límite";
  $("#academicWelcome").textContent = staff ? `Gestión académica · ${perfil.nombre}` : `Hola, ${perfil.nombre}`;
  $("#academicSummary").textContent = staff ? "Publica actividades de tus materias y revisa las entregas verificables." : `Tus actividades corresponden a ${perfil.ciclo_actual || "tu ciclo asignado"}.`;
  if (staff) $("#herramientasDocente").hidden = false;

  async function rubricasPorTarea(ids) { if (!ids.length) return new Map(); const { data } = await cliente.from("rubricas_tarea").select("tarea_id,criterio,puntaje_maximo,orden").in("tarea_id", ids).order("orden"); return (data || []).reduce((m, r) => { m.set(r.tarea_id, [...(m.get(r.tarea_id) || []), r]); return m; }, new Map()); }
  async function cargarTareas() {
    const { data: tareas, error } = await cliente.from("tareas_academicas").select("*").eq("activo", true).order("fecha_limite", { ascending: true }); const host = $("#listaTareas");
    if (error) { host.innerHTML = '<p class="academic-empty">Ejecuta el SQL actualizado para activar tareas.</p>'; return; }
    const [{ data: entregas }, rubricas] = await Promise.all([cliente.from("entregas_tareas").select("*").eq("estudiante_id", user.id), rubricasPorTarea((tareas || []).map(t => t.id))]); const porTarea = new Map((entregas || []).map(e => [e.tarea_id, e]));
    host.innerHTML = (tareas || []).map(t => { const entrega = porTarea.get(t.id), criterios = rubricas.get(t.id) || []; return `<article class="academic-item"><h3>${esc(t.titulo)}</h3><p><strong>${esc(t.ciclo)} · ${esc(t.materia)}</strong></p><p>${esc(t.instrucciones)}</p><p class="due">Entrega: ${fecha(t.fecha_limite)}</p>${t.enlace_referencia ? `<a class="text-link" href="${esc(t.enlace_referencia)}" target="_blank" rel="noopener">Material de referencia →</a>` : ""}${criterios.length ? `<span class="rubric-tag">Rúbrica de evaluación</span><ul class="rubric-list">${criterios.map(r => `<li>${esc(r.criterio)} · ${r.puntaje_maximo} pts</li>`).join("")}</ul>` : ""}${entrega ? `<span class="score">${esc(entrega.estado)}${entrega.calificacion !== null ? ` · Nota ${entrega.calificacion}/20` : ""}</span><p>${esc(entrega.comentario_docente || "")}</p>` : `<form data-entrega="${t.id}"><textarea name="comentario" placeholder="Comentario para el docente"></textarea><input name="enlace" type="url" placeholder="Enlace de tu archivo (opcional)"><input name="archivo" type="file"><button class="account-action">Entregar tarea</button></form>`}</article>`; }).join("") || '<p class="academic-empty">No hay tareas publicadas para tu ciclo.</p>';
    host.querySelectorAll("form[data-entrega]").forEach(f => f.addEventListener("submit", entregarTarea));
  }
  async function entregarTarea(e) { e.preventDefault(); const f = e.currentTarget, b = f.querySelector("button"); b.disabled = true; let enlace = f.enlace.value.trim(); const archivo = f.archivo.files[0]; if (archivo) { const ruta = `${user.id}/${Date.now()}-${archivo.name.replace(/[^\w.-]/g, "_")}`; const { error } = await cliente.storage.from("entregas-tareas").upload(ruta, archivo); if (error) { alert(error.message); b.disabled = false; return; } enlace = `storage:${ruta}`; } const { error } = await cliente.from("entregas_tareas").insert({ tarea_id: Number(f.dataset.entrega), estudiante_id: user.id, enlace_archivo: enlace || null, comentario_estudiante: f.comentario.value.trim() || null }); if (error) alert("No se pudo entregar: " + error.message); await cargarTareas(); }
  async function cargarEvaluaciones() { const { data: lista, error } = await cliente.from("evaluaciones").select("*").eq("activo", true).order("creado_en", { ascending: false }); const host = $("#listaEvaluaciones"); if (error) { host.innerHTML = '<p class="academic-empty">Ejecuta el SQL actualizado para activar evaluaciones.</p>'; return; } const { data: intentos } = await cliente.from("intentos_evaluacion").select("*").eq("estudiante_id", user.id); const realizados = new Map((intentos || []).map(i => [i.evaluacion_id, i])); host.innerHTML = (lista || []).map(ev => { const intento = realizados.get(ev.id); return `<article class="academic-item"><h3>${esc(ev.titulo)}</h3><p><strong>${esc(ev.ciclo)} · ${esc(ev.materia)}</strong></p><p>${esc(ev.instrucciones || "Responde las preguntas y envía una sola vez.")}</p>${intento ? `<span class="score">Resultado: ${intento.puntaje}/${intento.puntaje_maximo}</span>` : `<button class="account-action" type="button" data-evaluacion="${ev.id}">Iniciar evaluación</button><div id="evaluacion-${ev.id}"></div>`}</article>`; }).join("") || '<p class="academic-empty">No hay evaluaciones para tu ciclo.</p>'; host.querySelectorAll("[data-evaluacion]").forEach(b => b.addEventListener("click", abrirEvaluacion)); }
  async function abrirEvaluacion(e) { const b = e.currentTarget, id = Number(b.dataset.evaluacion), host = $("#evaluacion-" + id); b.disabled = true; const { data: preguntas, error } = await cliente.rpc("preguntas_para_evaluacion", { evaluacion_busqueda: id }); if (error) { host.innerHTML = '<p class="academic-empty">No se pudo abrir la evaluación.</p>'; return; } host.innerHTML = `<form data-form-evaluacion="${id}">${(preguntas || []).map(p => `<div class="question"><strong>${esc(p.enunciado)}</strong>${(p.opciones || []).map((op, i) => `<label><input required type="radio" name="p-${p.id}" value="${i}"> ${esc(op)}</label>`).join("")}</div>`).join("")}<button class="account-action">Enviar evaluación</button></form>`; host.querySelector("form").addEventListener("submit", enviarEvaluacion); }
  async function enviarEvaluacion(e) { e.preventDefault(); const form = e.currentTarget, id = Number(form.dataset.formEvaluacion), respuestas = {}; new FormData(form).forEach((v, k) => { if (k.startsWith("p-")) respuestas[k.slice(2)] = Number(v); }); const { data, error } = await cliente.rpc("enviar_evaluacion", { evaluacion_busqueda: id, respuestas_enviadas: respuestas }); if (error) { alert(error.message); return; } const r = data?.[0]; alert(`Evaluación enviada. Puntaje: ${r?.puntaje ?? 0}/${r?.puntaje_maximo ?? 0}`); cargarEvaluaciones(); }
  async function cargarEntregas() { if (!staff) return; const [{ data, error }, { data: personas }] = await Promise.all([cliente.from("entregas_tareas").select("id,tarea_id,estudiante_id,comentario_estudiante,enlace_archivo,estado,calificacion,tareas_academicas(titulo,ciclo,materia)").order("entregado_en", { ascending: false }), cliente.from("perfiles").select("id,nombre")]); const host = $("#listaEntregas"); if (error) { host.innerHTML = '<p class="academic-empty">Las entregas aparecerán cuando se active el SQL.</p>'; return; } const nombres = new Map((personas || []).map(p => [p.id, p.nombre])); host.innerHTML = (data || []).map(x => `<article class="academic-item"><h3>${esc(x.tareas_academicas?.titulo || "Tarea")}</h3><p><strong>${esc(nombres.get(x.estudiante_id) || "Estudiante")}</strong> · ${esc(x.comentario_estudiante || "Sin comentario")}</p>${x.enlace_archivo ? `<p>Archivo: ${esc(x.enlace_archivo)}</p>` : ""}<form data-revision="${x.id}"><select name="estado"><option value="revisado">Revisado</option><option value="requiere_correccion">Requiere corrección</option></select><input name="nota" type="number" min="0" max="20" step=".1" value="${x.calificacion ?? ""}" placeholder="Nota /20"><textarea name="comentario" placeholder="Comentario para el estudiante"></textarea><button class="account-action">Guardar revisión</button></form></article>`).join("") || '<p class="academic-empty">Aún no hay entregas.</p>'; host.querySelectorAll("form[data-revision]").forEach(f => f.addEventListener("submit", revisarEntrega)); }
  async function revisarEntrega(e) { e.preventDefault(); const f = e.currentTarget, { error } = await cliente.from("entregas_tareas").update({ estado: f.estado.value, calificacion: f.nota.value ? Number(f.nota.value) : null, comentario_docente: f.comentario.value.trim() || null, revisado_en: new Date().toISOString() }).eq("id", f.dataset.revision); if (error) alert(error.message); else cargarEntregas(); }
  function construirPregunta() { const host = $("#constructorPreguntas"), n = host.children.length + 1, caja = document.createElement("section"); caja.className = "question-builder"; caja.innerHTML = `<h3>Pregunta ${n}</h3><textarea name="pregunta" required placeholder="Enunciado de la pregunta"></textarea><input name="opciones" required placeholder="Opciones separadas por |"><input name="correcta" type="number" min="1" value="1" required placeholder="Número de opción correcta"><input name="puntos" type="number" min=".5" step=".5" value="1" required placeholder="Puntos">${n > 1 ? '<button type="button" class="secondary-action">Quitar pregunta</button>' : ""}`; caja.querySelector("button")?.addEventListener("click", () => caja.remove()); host.appendChild(caja); }
  if (staff) { $("#revisionDocente").hidden = false; construirPregunta(); $("#agregarPregunta").addEventListener("click", construirPregunta); $("#formTarea").addEventListener("submit", async e => { e.preventDefault(); const d = new FormData(e.currentTarget), { data, error } = await cliente.from("tareas_academicas").insert({ ciclo: d.get("ciclo"), materia: d.get("materia"), titulo: d.get("titulo"), instrucciones: d.get("instrucciones"), fecha_limite: d.get("fecha") || null, enlace_referencia: d.get("referencia") || null, creado_por: user.id }).select("id").single(); if (error) { alert(error.message); return; } const criterios = d.get("rubrica").split("|").map(x => x.trim()).filter(Boolean); if (criterios.length) await cliente.from("rubricas_tarea").insert(criterios.map((criterio, orden) => ({ tarea_id: data.id, criterio, puntaje_maximo: Math.round((20 / criterios.length) * 100) / 100, orden: orden + 1 }))); e.currentTarget.reset(); await cargarTareas(); }); $("#formEvaluacion").addEventListener("submit", async e => { e.preventDefault(); const f = e.currentTarget, d = new FormData(f), preguntas = [...f.querySelectorAll(".question-builder")].map((caja, orden) => ({ evaluacion_id: 0, enunciado: caja.querySelector('[name="pregunta"]').value.trim(), opciones: caja.querySelector('[name="opciones"]').value.split("|").map(x => x.trim()).filter(Boolean), respuesta_correcta: Number(caja.querySelector('[name="correcta"]').value) - 1, puntos: Number(caja.querySelector('[name="puntos"]').value), orden: orden + 1 })); if (preguntas.some(p => p.opciones.length < 2 || p.respuesta_correcta < 0 || p.respuesta_correcta >= p.opciones.length)) return alert("Revisa las opciones y la respuesta correcta de cada pregunta."); const { data, error } = await cliente.from("evaluaciones").insert({ ciclo: d.get("ciclo"), materia: d.get("materia"), titulo: d.get("titulo"), instrucciones: d.get("instrucciones") || null, creado_por: user.id }).select("id").single(); if (error) { alert(error.message); return; } const { error: ep } = await cliente.from("preguntas_evaluacion").insert(preguntas.map(p => ({ ...p, evaluacion_id: data.id }))); if (ep) alert(ep.message); else { f.reset(); $("#constructorPreguntas").innerHTML = ""; construirPregunta(); await cargarEvaluaciones(); } }); }
  await Promise.all([cargarTareas(), cargarEvaluaciones(), cargarEntregas()]);
});
