document.addEventListener("DOMContentLoaded", async () => {
  const cliente = window.STESIN_SUPABASE, lista = document.getElementById("listaAsistencia"), titulo = document.getElementById("asistenciaPorcentaje"), resumen = document.getElementById("asistenciaResumen");
  if (!cliente || !lista || !titulo || !resumen) return;
  const {data:{user}={}}=await cliente.auth.getUser(); if(!user)return;
  const {data:perfil}=await cliente.from("perfiles").select("rol,activo").eq("id",user.id).single(); if(!perfil?.activo||!["admin","docente"].includes(perfil.rol))return location.replace("index.html");
  document.title="Asistencia por materia | STESIN"; document.querySelector("header h1").textContent="Asistencia por materia"; document.querySelector("header p").textContent="Registra la participación por fecha, ciclo y materia asignada.";
  const controles=document.createElement("div"); controles.className="attendance-controls"; controles.innerHTML='<input type="date" class="attendance-date" id="fechaAsistencia"><select class="attendance-date" id="materiaAsistencia"></select><button class="account-action" id="exportarAsistencia" type="button">Descargar CSV</button>';
  resumen.textContent="Selecciona una materia y registra la participación de tus estudiantes.";resumen.insertAdjacentElement("afterend",controles);
  const fecha=controles.querySelector("#fechaAsistencia"),materia=controles.querySelector("#materiaAsistencia"),exportar=controles.querySelector("#exportarAsistencia");fecha.value=new Date().toISOString().slice(0,10);let estudiantes=[],registros=new Map(),asignaciones=[];
  const etiqueta=(a)=>`${a.ciclo} · ${a.materia}`;
  const {data:datosAsignacion,error:errAsignacion}=await cliente.from("materias_docentes").select("ciclo,materia").eq(perfil.rol==="docente"?"docente_id":"docente_id",perfil.rol==="docente"?user.id:user.id);
  if(perfil.rol==="admin"){const {data:todos}=await cliente.from("materias_docentes").select("ciclo,materia");asignaciones=todos||[];}else asignaciones=datosAsignacion||[];
  if(!asignaciones.length&&perfil.rol==="admin")asignaciones=[{ciclo:"Ciclo V",materia:"General"}];
  if(!asignaciones.length){lista.innerHTML='<p class="announcements-empty">Aún no tienes materias asignadas. Un administrador debe asignártelas en Administración.</p>';return;}
  materia.innerHTML=asignaciones.map((a,i)=>`<option value="${i}">${etiqueta(a)}</option>`).join("");
  async function cargar(){lista.innerHTML='<p class="announcements-empty">Cargando estudiantes…</p>';const actual=asignaciones[Number(materia.value)]||asignaciones[0];const [{data:alumnos,error},{data:datos}]=await Promise.all([cliente.from("perfiles").select("id,nombre,activo,rol").eq("rol","estudiante").eq("activo",true).order("nombre"),cliente.from("asistencia").select("estudiante_id,presente,nota").eq("fecha",fecha.value).eq("materia",actual.materia)]);if(error){lista.innerHTML='<p class="announcements-empty">Ejecuta el SQL de la Etapa 2 para habilitar asistencia por materia.</p>';return;}estudiantes=alumnos||[];registros=new Map((datos||[]).map(r=>[r.estudiante_id,r]));const presentes=[...registros.values()].filter(r=>r.presente).length;titulo.textContent=`${presentes} de ${estudiantes.length} presentes · ${actual.materia}`;lista.innerHTML=estudiantes.map(e=>{const r=registros.get(e.id),presente=r?.presente===true;return `<article class="attendance-row"><div><strong>${e.nombre}</strong><small>${r?(presente?"Presente":"Inasistencia"):"Sin registrar"}</small></div><button class="account-action ${presente?"":"danger"}" type="button" data-id="${e.id}" data-presente="${presente}">${presente?"Marcar falta":"Marcar presente"}</button></article>`;}).join("")||'<p class="announcements-empty">No hay estudiantes activos.</p>';lista.querySelectorAll("button[data-id]").forEach(b=>b.addEventListener("click",async()=>{b.disabled=true;const presente=b.dataset.presente!=="true";const {error:guardar}=await cliente.from("asistencia").upsert({estudiante_id:b.dataset.id,fecha:fecha.value,presente,ciclo:actual.ciclo,materia:actual.materia,docente_id:user.id},{onConflict:"estudiante_id,fecha,materia"});if(guardar)alert("No se pudo guardar: "+guardar.message);cargar();}));}
  fecha.addEventListener("change",cargar);materia.addEventListener("change",cargar);exportar.addEventListener("click",()=>{const actual=asignaciones[Number(materia.value)]||asignaciones[0],filas=[["Fecha","Ciclo","Materia","Estudiante","Estado"]].concat(estudiantes.map(e=>[fecha.value,actual.ciclo,actual.materia,e.nombre,registros.get(e.id)?.presente?"Presente":"Inasistencia"]));const csv="\uFEFF"+filas.map(f=>f.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`asistencia-${fecha.value}-${actual.materia}.csv`;a.click();URL.revokeObjectURL(a.href);});
  await cargar();
});
