document.addEventListener("DOMContentLoaded", async () => {
  const cliente=window.STESIN_SUPABASE,form=document.getElementById("formAviso"),lista=document.getElementById("listaAvisosAdmin"),resultado=document.getElementById("resultadoAviso");
  if(!cliente||!form||!lista||localStorage.getItem("rolUsuario")!=="admin")return;
  if(!document.getElementById("avisoAudiencia")){const destino=document.createElement("label");destino.innerHTML='Destinatarios<select id="avisoAudiencia"><option value="todos">Toda la comunidad</option><option value="estudiantes">Solo estudiantes</option><option value="docentes">Solo docentes</option><option value="administradores">Solo administración</option></select>';form.querySelector("button").insertAdjacentElement("beforebegin",destino);const ciclo=document.createElement("label");ciclo.innerHTML='Ciclo (opcional)<select id="avisoCiclo"><option value="">Todos los ciclos</option><option>Ciclo I</option><option>Ciclo II</option><option>Ciclo III</option><option>Ciclo IV</option><option>Ciclo V</option><option>Ciclo VI</option><option>Ciclo VII</option><option>Ciclo VIII</option></select>';destino.insertAdjacentElement("afterend",ciclo);}
  const escapar=(texto="")=>String(texto).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]));
  const mostrar=(texto,error=false)=>{resultado.hidden=false;resultado.textContent=texto;resultado.classList.toggle("error",error)};
  async function cargar(){const {data,error}=await cliente.from("avisos").select("id,titulo,mensaje,activo,destacado,audiencia,ciclo,creado_en").order("creado_en",{ascending:false});if(error){lista.innerHTML='<div class="admin-state">Ejecuta el SQL de la Etapa 2 para activar los avisos segmentados.</div>';return;}lista.innerHTML=(data||[]).map(a=>`<article class="resource-row"><div><h3>${escapar(a.titulo)}</h3><p>${escapar(a.mensaje)}</p><p>${a.activo?"Visible":"Oculto"}${a.destacado?" · Destacado":""} · ${escapar(a.audiencia||"todos")}</p></div><button class="account-action ${a.activo?"danger":""}" type="button" data-aviso="${a.id}" data-activo="${a.activo}">${a.activo?"Ocultar":"Publicar"}</button></article>`).join("")||'<div class="admin-state">No hay avisos publicados.</div>';lista.querySelectorAll("[data-aviso]").forEach(b=>b.addEventListener("click",async()=>{const {error}=await cliente.from("avisos").update({activo:b.dataset.activo!=="true"}).eq("id",b.dataset.aviso);if(error)return alert(error.message);cargar()}));}
  form.addEventListener("submit",async e=>{e.preventDefault();const titulo=document.getElementById("avisoTitulo").value.trim(),mensaje=document.getElementById("avisoMensaje").value.trim(),destacado=document.getElementById("avisoDestacado").checked,audiencia=document.getElementById("avisoAudiencia").value,ciclo=document.getElementById("avisoCiclo").value;const {error}=await cliente.from("avisos").insert({titulo,mensaje,destacado,audiencia,ciclo:ciclo||null});if(error)return mostrar("No se pudo publicar: "+error.message,true);form.reset();mostrar("Aviso publicado para: "+(ciclo||audiencia)+".");cargar();});
  cargar();
});
